apiVersion: apps/v1
kind: Deployment
metadata:
  name: simple-profile-dashboard
  labels:
    app: simple-profile-dashboard
spec:
  replicas: 3
  selector:
    matchLabels:
      app: simple-profile-dashboard
  template:
    metadata:
      labels:
        app: simple-profile-dashboard
    spec:
      containers:
      - name: simple-profile-dashboard
        image: kevinavicenna/simple-profile-dashboard:latest
        resources:
          requests:
            cpu: "250m"
            memory: "128Mi"
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 80
