apiVersion: v1
kind: Service
metadata:
  name: simple-profile-dashbard-service
spec:
  selector:
    app: simple-profile-dashboard
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: NodePort
